### ISSUE TITLE
Need more examples

### ISSUE THREAD

**Issue by nofe1248** [TomashuTTTT7/brigadier-plusplus#1]
I'm quite interested in your excellent work. But I also got quite confused with the grammar of registering a command tree. Could you provide some more complex examples of it?

**Comment by TomashuTTTT7** [comment]
Hello, you can see some examples in [tests](https://github.com/TomashuTTTT7/brigadier-plusplus/blob/master/brigadier-plusplus-test/brigadier/CommandDispatcher.hpp). It is pretty much analogical to java version with some syntax differences, so if you want to see how to create different node structures i suggest looking at java code that uses brigadier, e.g. minecraft decompilation. If you have more questions, go ahead.

**Comment by nofe1248** [comment]
Thanks. It's exactly what I wanted.
And thank you for making this fascinating work again.
